spring:
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  resources:
    static-locations: classpath:/, classpath:/static/
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  freemarker:
#    # 是否允许HttpServletRequest属性覆盖(隐藏)控制器生成的同名模型属性。
#    allow-request-override: false
#    # 是否允许HttpSession属性覆盖(隐藏)控制器生成的同名模型属性。
#    allow-session-override: false
#    # 是否启用模板缓存。
#    cache: false
#    # 模板编码。
#    charset: UTF-8
#    # 是否检查模板位置是否存在。
#    check-template-location: true
#    # Content-Type value.
#    content-type: application/x-msdownload
#    # 是否启用freemarker
#    enabled: true
#    # 设定所有request的属性在merge到模板的时候，是否要都添加到model中.
#    expose-request-attributes: false
#    # 是否在merge模板的时候，将HttpSession属性都添加到model中
#    expose-session-attributes: false
#    # 设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
#    expose-spring-macro-helpers: true
#    # 是否优先从文件系统加载template，以支持热加载，默认为true
#    prefer-file-system-access: true
#    # 设定模板的后缀.
#    suffix: .ftl
#    # 设定模板的加载路径，多个以逗号分隔，默认:
#    template-loader-path: classpath:/templates/
#    # 设定FreeMarker keys.
#    settings:
#      classic_compatible: true #处理空值
#      datetime_format: yyy-MM-dd HH:mm
#      number_format: 0.##
#      default_encoding: UTF-8
  redis:
    database: 0
    host: 219.141.235.67
    port: 43967
    password: KH_ZingerH189QsT
    namespace: "zinger-customer"
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8   # 连接池中的最大空闲连接 默认 8
        min-idle: 0   # 连接池中的最小空闲连接 默认 0
  datasource:
    dynamic:
      #主数据源
      lazy: false
      primary: impala
      strict: true
      datasource:
        #数据源1
        mysql:
#          开发环境
          url: jdbc:mysql://219.141.235.67:41036/zinger
          username: zinger
          password: kh_Zinger$#321
          driver-class-name: com.mysql.cj.jdbc.Driver
#          测试环境
#          url: jdbc:mysql://172.18.17.15:25615/zinger-test
#          username: zinger
#          password: Zinger$#kh_321
#          driver-class-name: com.mysql.cj.jdbc.Driver
        #数据源2
        impala:
          driver-class-name: com.cloudera.impala.jdbc.Driver
          url: jdbc:impala://172.18.17.47:21050/default;
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-on-borrow: false
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
      #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
      test-while-idle: true
      # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
      #validationQuery参数必须设置为非空字符串
      test-on-return: false
      # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
      #如果指定,则查询必须是一个SQL SELECT并且必须返回  至少一行记录
      validation-query: select 1
      filters: stat
      initialSize: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connectionSize: 200


tldSkipPatterns: jaxb-impl-*.jar,jaxb-core-*.jar,activation.jar,metadata-extractor-*.jar,juh-*.jar,jurt-*.jar

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
  endpoint:
    health:
      show-details: always

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:/mapper/**/*Dao.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0 # 逻辑已删除值(默认为 1)
    #logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    #自定义填充策略接口实现
    #    meta-object-handler: com.zhengqing.config.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    #    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 解决oracle更新数据为null时无法转换报错，mysql不会出现此情况
    jdbc-type-for-null: 'null'
  configuration-properties:
    impala-sechema: test_user_info
    label-data-sechema: dev_dwd_zinger_relation

config:
  app-name: zinger-customer
  digest-type: sm3
  default-page-size: 30
  jwt-signkey: 43f7ae8d-a060-4e24-b15c-78e344c6e79b
  swagger:
    title: Cloud-UC接口文档
    description: Cloud-UC接口文档
    version: 1.0.0
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
    enable: true
  fanruan:
    report-url: https://rancher.kuangheng.com/report/decision
    bi-url: https://rancher.kuangheng.com/bi/decision
    token-key: FineReport2018
    expire-milli-seconds: 300000
  minio:
    endpoint: 172.18.17.16:59029,172.18.17.14:59029
    accessKey: iadmin321
    accessSecret: ca531e34c5b64cca971c43e78290aa27
    bucketName: test
    region:

service-api:
  uc: https://rancher.kuangheng.com


